class ReadList:
    CHANGE_PARAMETERS = 0
    SEND_PARAMETERS = 1
    START_PROCESS = 178
    ABORT_PROCESS = 188

class WriteList:
    SEND_PARAMETERS = 1
    SENSOR_VALUES = 2
    SEND_ACTUATORS = 3
    HEARTBEAT = 255